spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    format_sql: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/eve-tools
    username: root
    password: root
